# setup script for the Cascadia project
setwd("~/Uni/NTNU/Masters Project/CSZ/R")

# install required packages if necessary
if(F) {
  install.packages("Matrix")
  install.packages("spam")
  install.packages("fields")
  install.packages("latex2exp")
  install.packages("xtable")
  install.packages("profvis")
  install.packages("viridis")
  install.packages("numDeriv")
  install.packages("INLA",
                   repos=c(getOption("repos"),
                           INLA="https://inla.r-inla-download.org/R/stable"),
                   dep=TRUE)
  install.packages("data.table")
  install.packages("devtools")
  install.packages("ggplot2")
  install.packages("colorspace")
  install.packages("TMB")
  install.packages("plyr")
  install.packages("sf")
  install.packages("ncdf4")
  install.packages("pracma")
  install.packages("concaveman")
  install.packages("maps")
  install.packages("mapproj")
  install.packages("mapdata")
  install.packages("sp")
  install.packages("raster")
  install.packages("geodata")
  install.packages("dplyr")
  install.packages("stringr")
  install.packages("smoothr")
  install.packages("units")
  install.packages("rmapshaper")
  install.packages("metR")
  install.packages("stars")
  install.packages("rSPDE")
  install.packages("inlabru")
  install.packages("tidyr")
  install.packages("MASS")
  install.packages("matrixcalc")
  install.packages("akima")
  install.packages("scico")
  install.packages("geosphere")
  install.packages("rootSolve")
  install.packages("ggspatial")
  install.packages("pracma")
  install.packages("sfheaders")
  install.packages('geometry')
  install.packages("gridExtra")
  install.packages("fmesher")
  install.packages("scoringRules")
  install.packages("scoringutils")
  install.packages("ggrepel")
  install.packages("scales")
  install.packages("rcartocolor")
}

# load required packages and R scripts
library(Matrix)
library(spam)
library(fields)
library(latex2exp)
library(xtable)
library(profvis)
library(viridis)
library(numDeriv)
library(INLA)
library(data.table)
library(devtools)
library(ggplot2)
library(colorspace)
library(TMB)
library(plyr)
library(sf)
library(ncdf4)
library(pracma)
library(concaveman)
library(maps)
library(mapproj)
library(mapdata)
library(sp)
library(raster)
library(geodata)
library(dplyr)
library(stringr)
library(smoothr)
library(units)
library(rmapshaper)
library(metR)
library(stars)
library(rSPDE)
library(inlabru)
library(tidyr)
library(MASS)
library(matrixcalc)
library(akima)
library(scico)
library(geosphere)
library(rootSolve)
library(ggspatial)
library(pracma)
library(sfheaders)
library(geometry)
library(gridExtra)
library(fmesher)
library(scoringRules)
library(scoringutils)
library(ggrepel)
library(scales)
library(rcartocolor)


options(warn=1)

source("Code/slab.R")
source("Code/okada.R")
source("Code/okadaMatrix.R")
source("Code/plotter.R")
source("Code/spde_mesh.R")
source("Code/utilityFuns.R")
source("Code/resultsHandling.R")



