language: r

sudo: false

cache: packages

dist: xenial

os:
  - linux

jobs:
  include:

    - stage: Install package dependencies
      r: devel
      install:
        - ./bin/install_dependencies.sh
      script: true

    - stage: Install package dependencies
      r: release
      install:
        - ./bin/install_dependencies.sh
      script: true

    - stage: Install and check the package
      r: devel
      install: true
      script:
        - export TMB_AD_FRAMEWORK=TMBad
        - ./bin/install_and_check.sh

    - stage: Install and check the package
      r: release
      install: true
      script:
        - export TMB_AD_FRAMEWORK=CppAD
        - ./bin/install_and_check.sh

    - stage: Run more checks
      r: devel
      install: true
      script:
        - export TMB_AD_FRAMEWORK=TMBad
        - ./bin/run_more_checks.sh

    - stage: Run more checks
      r: release
      install: true
      script:
        - export TMB_AD_FRAMEWORK=CppAD
        - ./bin/run_more_checks.sh

    - stage: Run full example suite
      r: devel
      install: true
      script:
        - export TMB_AD_FRAMEWORK=TMBad
        - ./bin/run_full_example_suite.sh

    - stage: Run full example suite
      r: release
      install: true
      script:
        - export TMB_AD_FRAMEWORK=CppAD
        - ./bin/run_full_example_suite.sh

    - stage: Build and deploy documentation
      r: devel
      install:
        - wget http://www.student.dtu.dk/~kaskr/doxygen-1.8.12.linux.bin.tar.gz
        - tar zxf doxygen-1.8.12.linux.bin.tar.gz
        - export PATH=`pwd`/doxygen-1.8.12/bin:$PATH
        - doxygen -v
        - wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-linux-amd64.tar.gz
        - tar zxf pandoc-2.11.2-linux-amd64.tar.gz
        - export PATH=`pwd`/pandoc-2.11.2/bin:$PATH
        - pandoc -v
      script:
        - export TMB_AD_FRAMEWORK=TMBad
        - make doxygen
        - ./bin/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_failure:
  - cat /home/travis/build/kaskr/adcomp/TMB.Rcheck/00install.out
  - cat /home/travis/build/kaskr/adcomp/TMB.Rcheck/00check.log

addons:
  apt:
    packages:
##      - doxygen
      - pandoc
      - graphviz
      - librsvg2-dev

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "kaskr@dtu.dk"
